[tool.poetry]
name = "caption-editor-api"
version = "0.1.1"
description = "Caption Editor API Server - FastAPI backend for video caption processing"
authors = ["Caption Editor Team"]
packages = [{include = "caption_editor_api", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.0"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
pydantic = "^2.5.0"
python-multipart = "^0.0.6"
httpx = "^0.25.0"
assemblyai = "^0.42.1"
pyyaml = "^6.0.1"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
black = "^23.0.0"
ruff = "^0.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"